### ISSUE TITLE
Copyrigth section is missing

### ISSUE THREAD

**Issue by salmoh** [ubuntu-ir/traktor#16]
Copyright section is files is missing. It is advisable to add contributers there.

**Comment by salmoh** [comment]
@AmirrezaFiroozi please add your name and your email on top of the files your edit. like

#!/bin/sh
#
#    Copyright (C) 2016  My Name <example@example.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA

**Comment by danialbehzadi** [comment]
A project-wide license is set.
