### ISSUE TITLE
عدم توانایی در تشخیص توزیع

### ISSUE THREAD

**Issue by amin0256** [ubuntu-ir/traktor#19]
با سلام
من در توزیع اوبونتو نگارش ۱۶.۰۴ وقتی تراکتور را اجرا میکنم، سعی دراجرای traktor_arch.sh داره که خب احتمالا بنظرم باید نسخه دبیان رو اجرا کنه.
اگر نیاز به توضیح بیشتر هست، بفرمایید تا اضافه کنم.

**Comment by shadowm2** [comment]
این مشکل رو من هم داشتم که درستش کردم
pull request دادم منتظرم

**Comment by salmoh** [comment]
@shadowm2 which commit are you talking about?

**Comment by amin0256** [comment]
@salmoh this issue fixed in pull request #20. Please close this issue.
