### ISSUE TITLE
مشکل با فایرفاکس

### ISSUE THREAD

**Issue by amim021** [ubuntu-ir/traktor#33]
من نمیتونم از تور روی فایرفاکس استفاده کنم .
 افزونه  foxyproxy 
رو روی ۱۲۷.۰.۰.۱:۹۰۵۰ تنظیم میکنم ولی بازم نمیتونم از تور سرویس بگیرم.

**Comment by xtoolkit** [comment]
سلام
شما نیازی به هیچ افزونه ای ندارید
اگه تراکتور رو نصب کرده باشید کل سیستمتون میره زیر شبکه تور
اما اگه مطمئن هستید تور به ۱۰۰٪ رسیده تنظیمات زیر رو تو فایرفاکستون اعمال کنید
![sketch](https://cloud.githubusercontent.com/assets/8210666/20859184/ecd72418-b96c-11e6-8861-bba7a547fa86.png)

**Comment by danialbehzadi** [comment]
‫نیازی به انجام هیچ کاری در فایرفاکس نیست. فقط مطمئن شوید تنظیمات شبکهٔ فایرفاکس روی Use system proxy settings قرار گرفته باشه.
