### ISSUE TITLE
مشکل 

### ISSUE THREAD

**Issue by amim021** [ubuntu-ir/traktor#34]
یه مشکله که دارم اینکه هیچ وقت درصد برام نمیاد حتی وقتی پل های مختلف رو استفاده میکنم .
بعضی وقتا به تور دسترسی دارم و بعضی وقتا هم دسترسی ندارم.
<a href="http://uupload.ir/view/zrb6_1.png" target="_blank"><img src="http://uupload.ir/files/zrb6_1_thumb.png" border="0" alt="آپلود عکس" /></a>

**Comment by danialbehzadi** [comment]
You should post the log. Systemd status is not useful at all.

**Comment by danialbehzadi** [comment]
Closed due to inactivity
