### ISSUE TITLE
connection failure error because of filternet in iran!

### ISSUE THREAD

**Issue by VahidSa** [ubuntu-ir/traktor#35]
i get connection failure error after run  torbrowser-launcher! and i'm sure my internet connection is ok!

`Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.6
https://github.com/micahflee/torbrowser-launcher
Downloading and installing Tor Browser for the first time.
Downloading https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
Download error: User timeout caused connection failure. <class 'twisted.internet.error.TimeoutError'>
`

i know it's because of filternet in iran! need to download something from torproject.org!
but i don't have any idea for solve it!
help me plz :(

![image](https://cloud.githubusercontent.com/assets/19525585/21001316/e7eca6d2-bd34-11e6-824e-2a20b8355713.png)

**Comment by danialbehzadi** [comment]
If traktor have been setup properly, it should automatically tunnel the download through tor network. Try openning a new terminal emulator window and see if it is going to be downloaded there or not. If that doesn't fix it, try logging out and in from your account.

در ۸ دسامبر ۲۰۱۶ ۱۱:۲۶:۲۶ (GMT+03:30)، VahidSa <notifications@github.com> نوشت:
>i get connection failure error after run  torbrowser-launcher! and i'm
>sure my internet connection is ok!
>
>`Tor Browser Launcher
>By Micah Lee, licensed under MIT
>version 0.2.6
>https://github.com/micahflee/torbrowser-launcher
>Downloading and installing Tor Browser for the first time.
>Downloading
>https://dist.torproject.org/torbrowser/update_2/release/Linux_x86_64-gcc3/x/en-US
>Download error: User timeout caused connection failure. <class
>'twisted.internet.error.TimeoutError'>
>`
>
>i know it's because of filternet in iran! need to download something
>from torproject.org!
>but i don't have any idea for solve it!
>help me plz :(
>
>
>
>![image](https://cloud.githubusercontent.com/assets/19525585/21001316/e7eca6d2-bd34-11e6-824e-2a20b8355713.png)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubuntu-ir/traktor/issues/35

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danialbehzadi** [comment]
Closed due to inactivity
