### ISSUE TITLE
چگونه خاموش کنیم!!!!

### ISSUE THREAD

**Issue by farhadhp** [ubuntu-ir/traktor#38]
سلام

حالا اگه بخواهیم تور رو خاموش کنیم چکار کنیم ؟

از قسمت 
Network 
و ترمینال هم سعی کردم ولی تور خاموش نشد !!!

**Comment by danialbehzadi** [comment]
‫درود.
‫تور رو که لازم نیست خاموش کنی. باید پروکسیت رو از روی تور برداری.
‫کافیه در org.gnome.system.proxy مقدار mode رو برابر "none" قرار بدی.
