### ISSUE TITLE
terminal proxy

### ISSUE THREAD

**Issue by elyas74** [ubuntu-ir/traktor#44]
when I first install `traktor` I can access filtered sites from browser and terminal, But after reboot, I just can access tor in my browser, any idea?

OS : ubuntu 16.04 unity

**Comment by danialbehzadi** [comment]
How did you install traktor? What is the outputs of this command?
    $ echo $http_proxy

**Comment by elyas74** [comment]
> How did you install traktor?

I clone repo and run install.sh with bash
(NOTE : I uninstall it one time with your uninstall_debian.sh script and install it again)

> What is the outputs of this command?
echo $http_proxy

http://127.0.0.1:8123/

**Comment by danialbehzadi** [comment]
> I clone repo and run install.sh with bash
(NOTE : I uninstall it one time with your uninstall_debian.sh script and install it again)

It is OK, but it's preferred to install traktor by PPA in Ubuntu.

> http://127.0.0.1:8123/

So it should be OK. Detail your problem.

**Comment by elyas74** [comment]
> Detail your problem.

what else exactly?

**Comment by danialbehzadi** [comment]
> what else exactly?

Say how do you know if it can not connect to tor in terminal?

**Comment by elyas74** [comment]
when I am connected to `tor` with `traktor` I can access for example [https://mongodb.com](https://mongodb.com), but in terminal when I `curl` or `elinks` it I get 403 error.

Or in browser I can access [https://facebook.com](https://facebook.com), but when I `curl` it I get nothing and when I ping it in terminal I receive `10.10.34.36` IP.

**Comment by danialbehzadi** [comment]
Maybe you uninstalled dnscrypt-proxy or configured an external proxy server?

**Comment by elyas74** [comment]
> dnscrypt-proxy is already the newest version (1.6.1-1).

and no other proxy set in my system.

I test this on another system and had same issue.

**Comment by danialbehzadi** [comment]
So, give me the log of dnscrypt-proxy

**Comment by elyas74** [comment]
I can't find the log file, is usefull? if not what is path of log file?
```
elyas@X240:~$ sudo service dnscrypt-proxy status
● dnscrypt-proxy.service - DNSCrypt proxy
   Loaded: loaded (/lib/systemd/system/dnscrypt-proxy.service; enabled; vendor preset: enabled)
   Active: active (running) since شنبه 2017-01-07 16:01:23 IRST; 6s ago
     Docs: man:dnscrypt-proxy(8)
 Main PID: 2915 (dnscrypt-proxy)
   CGroup: /system.slice/dnscrypt-proxy.service
           └─2915 /usr/sbin/dnscrypt-proxy --resolver-name=cisco

ژانویه 07 16:01:22 X240 dnscrypt-proxy[2915]: [WARNING] - [cisco] logs your activity - a different provider might be better
ژانویه 07 16:01:22 X240 dnscrypt-proxy[2915]: [NOTICE] Starting dnscrypt-proxy 1.6.1
ژانویه 07 16:01:22 X240 dnscrypt-proxy[2915]: [INFO] Generating a new session key pair
ژانویه 07 16:01:22 X240 dnscrypt-proxy[2915]: [INFO] Done
ژانویه 07 16:01:23 X240 dnscrypt-proxy[2915]: [INFO] Server certificate #1463092899 received
ژانویه 07 16:01:23 X240 dnscrypt-proxy[2915]: [INFO] This certificate is valid
ژانویه 07 16:01:23 X240 dnscrypt-proxy[2915]: [INFO] Chosen certificate #1463092899 is valid from [2016-05-13] to [2017-05-
ژانویه 07 16:01:23 X240 dnscrypt-proxy[2915]: [INFO] Server key fingerprint is ABA1:F000:D394:8045:672D:73E0:EAE6:F181:19D0
ژانویه 07 16:01:23 X240 dnscrypt-proxy[2915]: [NOTICE] Proxying from 127.0.2.1:53 to 208.67.220.220:443
ژانویه 07 16:01:23 X240 systemd[1]: Started DNSCrypt proxy.
```

**Comment by danialbehzadi** [comment]
What is the DNS Server in you connection's IPv4 Settings?

**Comment by elyas74** [comment]
```
elyas@X240:~$ cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 127.0.0.1
```

**Comment by danialbehzadi** [comment]
Temporary change this to 127.0.2.1 and see if it's OK or not.

**Comment by elyas74** [comment]
No, but see this :

```
elyas@X240:~$ host facebook.com
facebook.com has address 31.13.92.36
facebook.com has IPv6 address 2a03:2880:f11c:8083:face:b00c:0:25de
facebook.com mail is handled by 10 msgin.vvv.facebook.com.

elyas@X240:~$ curl facebook.com
# Gos to PEYVANDHA site

elyas@X240:~$ curl 31.13.92.36
# Nothing in output
```

Any idea?

**Comment by babayaga94** [comment]
چرا دو ایرانی باید انگلیسی با هم صحبت بکنن؟ واقعا برام جالبه بدونم

**Comment by salmoh** [comment]
زبون پیش‌فرض برای باگ‌ریپورت و برنامه‌نویسی انگلیسی هست.

**Comment by danialbehzadi** [comment]
@babayaga94 To make a searching and viewing record for all of the project's users.

**Comment by danialbehzadi** [comment]
Passed more than 3 month from last post, assuming it has been solved. If there is still problems, upgrade to Ubuntu 17.04 and file new issue.
