### ISSUE TITLE
miss file

### ISSUE THREAD

**Issue by kiamazi** [ubuntu-ir/traktor#76]
به نظر میاد فایل
tracktor_gui_panel.py
‫توی مخزن master نیست ولی برای نصب یکی از مراحل منتقل کردن همین فایله

**Comment by danialbehzadi** [comment]
That is WIP

در ۱۴ ژوئن ۲۰۱۷ ۱۵:۴۷:۳۷ (GMT+04:30)، kiamazi <notifications@github.com> نوشت:
>به نظر میاد فایل
>tracktor_gui_panel.py
>برای آپدیت آخر توی مخزن گیت نیست
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ubuntu-ir/traktor/issues/76

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
