### ISSUE TITLE
does it going to support other distros

### ISSUE THREAD

**Issue by MetaiR** [ubuntu-ir/traktor#87]
hello,
as I asked in title, does it going to support other Linuxes? for example `OpenSUSE`

**Comment by Sosha1996** [comment]
We have done this!

**Comment by MetaiR** [comment]
I saw it and installed it,
there is just two matters.
one: it doesn't have any GUI toolbar icon like debian.
two: it wasn't build for OpenSuse 42.3 (which came out recently) but it wasn't a problem because I changed the url addresses to from 42.2 to 42.3 and it installed completely.

the thing is I really need that toolbar icon. is there anything that I can do about it? (or am I missing something?)

**Comment by MetaiR** [comment]
I found it in other branch.

**Comment by Sosha1996** [comment]
Traktor GUI have sam bug.
I Create new traktor gui for users. This Traktor GUI will be better than the previous Traktor GUI...

**Comment by Sosha1996** [comment]
You can now see the traktor on the my [GitLab](https://gitlab.com/Sosha/traktor)...

**Comment by MetaiR** [comment]
unfortunately, the `AppIndicator3` dependency which is used in GUI, is not going to be installed in my os (OpenSUSE) and I can't use it....
this is the output of `pip` for installing `AppIndicator3`

```
Could not find a version that satisfies the requirement AppIndicator3 (from versions: )
No matching distribution found for AppIndicator3
```
