### ISSUE TITLE
PPA Error for ubuntu 17.04

### ISSUE THREAD

**Issue by hamidrezakp** [ubuntu-ir/traktor#91]
hi.
i got this error while updating ropes :
`Err:5 http://ppa.launchpad.net/dani.behzi/traktor/ubuntu artful Release                                  
  404  Not Found
E: The repository 'http://ppa.launchpad.net/dani.behzi/traktor/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

**Comment by danialbehzadi** [comment]
It should be fixed in an hour.
