### ISSUE TITLE
obfs4 bridges are old and disabled

### ISSUE THREAD

**Issue by virtualdemon** [ubuntu-ir/traktor#95]
Project bridges are old ; some of them are disabled . it's better to update the https://ubuntu-ir.github.io/traktor/torrc or write a script to get bridges by sending an email to bridges@torproject.org

**Comment by danialbehzadi** [comment]
Thanks for reaching, but this repo is dropped due to heavy changes in system files. The next generation of Traktor with no system change is developing here: https://gitlab.com/danialbehzadi/traktor-ng
